export const MOBILE_WEB_FIRST_PRODUCTION_BRIDGE_VERSION = 2
export const MOBILE_WEB_BRIDGE_FLOOR_RETENTION_STABLE_RELEASES = 2
export const MOBILE_WEB_PACKAGE_BRIDGE_RANGE = {
  minimum: 2,
  testedThrough: 2
} as const
