// Why this list lives in src/main rather than being imported from the CLI: the
// main tsconfig cannot see the CLI project. It is kept honest by
// src/cli/cli-command-name-parity.test.ts, which fails when COMMAND_SPECS grows
// a top-level command this list is missing — previously that drift was silent
// and the launch fell through to Chromium startup, which core-dumps on a
// headless or unsandboxed host instead of running the command.
//
// This module deliberately has no imports so the CLI tsconfig can list it
// without pulling anything else in.
export const CLI_COMMAND_NAMES = [
  'account',
  'agent',
  'agent-context',
  'artifacts',
  'automations',
  'back',
  'capture',
  'check',
  'claude-teams',
  'clear',
  'click',
  'clipboard',
  'computer',
  'console',
  'cookie',
  'dblclick',
  'diagnostics',
  'dialog',
  'download',
  'drag',
  'emulator',
  'environment',
  'eval',
  'exec',
  'file',
  'fill',
  'find',
  'focus',
  'forward',
  'full-screenshot',
  'geolocation',
  'get',
  'goto',
  'highlight',
  'hover',
  'inserttext',
  'intercept',
  'is',
  'keypress',
  'linear',
  'mouse',
  'network',
  'open',
  'orchestration',
  'pdf',
  'project',
  'reload',
  'repo',
  'screenshot',
  'scroll',
  'scrollintoview',
  'select',
  'select-all',
  'serve',
  'set',
  'skills',
  'snapshot',
  'status',
  'storage',
  'tab',
  'terminal',
  'type',
  'uncheck',
  'upload',
  'viewport',
  'vm',
  'wait',
  'worktree'
] as const
