import { readdir } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { isAutoGeneratedCreatureBranchName } from '../shared/branch-name-from-work'
import { getRepoExecutionHostId } from '../shared/execution-host'
import { isFolderRepo } from '../shared/repo-kind'
import type { GlobalSettings, Repo } from '../shared/types'
import {
  encodeClaudeProjectPath,
  isClaudeProjectDirInScope
} from './ai-vault/claude-project-dir-encoding'
import {
  computeRemoteWorktreePath,
  computeWorktreePath,
  getWorktreePathSettings,
  hasRepoWorktreeBasePath
} from './ipc/worktree-logic'
import { worktreePathComparisonKey } from './ipc/worktree-path-comparison'

const RETIREMENT_PROBE_NAME = 'orca-retirement-probe'
const scansByStore = new WeakMap<object, Map<string, Promise<Set<string>>>>()

type RetirementReadStore = {
  getRetiredWorktreeNames(repoId: string): string[]
}
type RetirementBackfillStore = {
  mergeRetiredWorktreeNames(repoId: string, names: Iterable<string>): boolean
}
type RetirementPathSettings = Pick<GlobalSettings, 'nestWorkspaces' | 'workspaceDir'>

/** Why reuse the auto-rename predicate: it already defines "a name Orca picked, not the user", is
 *  already tested, and a second definition here drifted — its `-([2-9]\d*)` never matched `-10`. */
export function normalizeRetirableGeneratedName(name: string): string | null {
  const normalized = name.trim().toLowerCase()
  if (normalized.length > 256) {
    return null
  }
  return isAutoGeneratedCreatureBranchName(normalized) ? normalized : null
}

/** Why: over-retiring costs one name from a 552-entry pool; under-retiring reissues a path whose
 *  agent history is still on disk. So this matches generously and never tries to be exact. */
export function collectRetiredNamesFromLeafNames(leafNames: Iterable<string>): Set<string> {
  const retired = new Set<string>()
  for (const leafName of leafNames) {
    if (typeof leafName !== 'string' || leafName.length === 0) {
      continue
    }
    const normalized = normalizeRetirableGeneratedName(leafName)
    if (normalized) {
      retired.add(normalized)
    }
  }
  return retired
}

/** The workspace leaf is whatever the bucket has beyond its encoded parent. Deriving it from
 *  trailing dash segments instead makes a numerically named workspace retire its parent
 *  directory's name — and `orca` is in the pool. The first segment is also offered because an
 *  agent run from a subdirectory buckets the whole subpath. */
export function extractBucketLeafCandidates(
  bucketName: string,
  encodedParents: readonly string[]
): string[] {
  const bucket = bucketName.toLowerCase()
  for (const parent of encodedParents) {
    if (!parent || bucket === parent || !isClaudeProjectDirInScope(bucket, [parent])) {
      continue
    }
    const remainder = bucket.slice(parent.length + 1)
    if (!remainder) {
      continue
    }
    const firstSegment = remainder.split('-')[0]
    return remainder === firstSegment ? [remainder] : [remainder, firstSegment]
  }
  return []
}

function getRetirementProbePath(repo: Repo, settings: RetirementPathSettings): string {
  const pathSettings = getWorktreePathSettings(repo, settings)
  return repo.connectionId
    ? computeRemoteWorktreePath(RETIREMENT_PROBE_NAME, repo.path, pathSettings, {
        useConfiguredAbsolutePath: hasRepoWorktreeBasePath(repo)
      })
    : computeWorktreePath(RETIREMENT_PROBE_NAME, repo.path, pathSettings)
}

// Why: for a WSL repo the probe path costs a blocking `wsl.exe` call, and the create path plus
// every suggestion refresh asks for the same key. Inputs are all the key derives from.
const COLLISION_KEY_CACHE_MAX = 512
const collisionKeyCache = new Map<string, string>()

export function resetRetirementCollisionKeyCacheForTests(): void {
  collisionKeyCache.clear()
}

/** Identifies the cwd namespace a repo creates workspaces into. Two repos that would place a
 *  workspace of the same name at the same path share retirements; independent paths do not. */
export function getRetirementCollisionKey(repo: Repo, settings: RetirementPathSettings): string {
  const hostId = getRepoExecutionHostId(repo)
  const cacheKey = [
    hostId,
    repo.path,
    repo.worktreeBasePath ?? '',
    settings.workspaceDir,
    settings.nestWorkspaces ? 'nested' : 'flat'
  ].join('\u0000')
  const cached = collisionKeyCache.get(cacheKey)
  if (cached !== undefined) {
    return cached
  }
  const key = `${hostId}:${worktreePathComparisonKey(getRetirementProbePath(repo, settings))}`
  if (collisionKeyCache.size >= COLLISION_KEY_CACHE_MAX) {
    collisionKeyCache.clear()
  }
  collisionKeyCache.set(cacheKey, key)
  return key
}

/** Stored per repo id, which is stable, but read across every repo that creates into the same cwd
 *  namespace — that is where a reissued name would actually collide.
 *
 *  The peer scan is deliberately lazy: a repo's own retirements never touch a path, and a peer's
 *  namespace is derived only once that peer is known to hold retirements. Deriving one costs a
 *  blocking `wsl.exe` call for a WSL repo, so it must not be paid per repo on every create. */
export function getRetiredWorktreeNamesForRepo(
  store: RetirementReadStore,
  repo: Repo,
  repos: readonly Repo[],
  settings: RetirementPathSettings
): string[] {
  if (isFolderRepo(repo)) {
    return []
  }
  const names = new Set(store.getRetiredWorktreeNames(repo.id))
  let collisionKey: string | null = null
  for (const candidate of repos) {
    if (candidate.id === repo.id || isFolderRepo(candidate)) {
      continue
    }
    const candidateNames = store.getRetiredWorktreeNames(candidate.id)
    if (candidateNames.length === 0) {
      continue
    }
    collisionKey ??= getRetirementCollisionKey(repo, settings)
    if (getRetirementCollisionKey(candidate, settings) !== collisionKey) {
      continue
    }
    for (const name of candidateNames) {
      names.add(name)
    }
  }
  return [...names]
}

function parentPath(path: string): string {
  const trimmed = path.replace(/[/\\]+$/, '')
  const separatorIndex = Math.max(trimmed.lastIndexOf('/'), trimmed.lastIndexOf('\\'))
  return separatorIndex < 0 ? '' : trimmed.slice(0, separatorIndex)
}

export function ensureRetiredWorktreeNamesBackfilled(
  store: RetirementBackfillStore,
  repo: Repo,
  settings: RetirementPathSettings
): Promise<void> {
  // Remote workspaces keep their agent state on the execution host, which this scan cannot see, so
  // a re-added SSH repo does not recover its retirements the way a local one does.
  if (isFolderRepo(repo) || repo.connectionId) {
    return Promise.resolve()
  }
  let storeScans = scansByStore.get(store)
  if (!storeScans) {
    storeScans = new Map()
    scansByStore.set(store, storeScans)
  }
  const collisionKey = getRetirementCollisionKey(repo, settings)
  let scan = storeScans.get(collisionKey)
  if (!scan) {
    scan = discoverRetiredWorktreeNames({
      workspaceRoots: [parentPath(getRetirementProbePath(repo, settings))]
    })
    storeScans.set(collisionKey, scan)
  }
  // Why the merge sits outside the cached promise: the scan is per cwd namespace but the registry
  // is per repo, so every repo that asks must receive it — not only the one that triggered it.
  return scan.then((names) => {
    store.mergeRetiredWorktreeNames(repo.id, names)
  })
}

async function readDirectoryNames(path: string): Promise<string[]> {
  try {
    const entries = await readdir(path, { withFileTypes: true })
    return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name)
  } catch {
    // Missing or unreadable roots are normal: the agent may never have run on this machine.
    return []
  }
}

/** Claude buckets its per-conversation state under a directory derived from the workspace cwd. A
 *  bucket surviving its workspace is exactly the evidence we need: the name was used, the
 *  directory is gone, and reissuing the name would hand the next occupant that conversation.
 *  CLAUDE_CONFIG_DIR relocates the whole state root, buckets included.
 *
 *  Codex is deliberately not scanned: it records the cwd inside
 *  `sessions/YYYY/MM/DD/rollout-*.jsonl` rather than in a directory name, so seeding from it would
 *  mean parsing user conversation files. Names spent only under Codex before this feature shipped
 *  stay issuable; every name spent after it is recorded at create time regardless of agent. */
function getClaudeProjectsDir(home: string, env: NodeJS.ProcessEnv): string {
  const override = env.CLAUDE_CONFIG_DIR?.trim()
  return override ? join(override, 'projects') : join(home, '.claude', 'projects')
}

/** Discovers names already spent for a repo, for the one-time seed of the retirement registry.
 *  Local and best-effort by design — agent state for an SSH workspace lives on the execution host,
 *  so names used only there stay issuable until this host observes them. */
export async function discoverRetiredWorktreeNames(args: {
  workspaceRoots: readonly string[]
  home?: string
  env?: NodeJS.ProcessEnv
}): Promise<Set<string>> {
  const leafNames: string[] = []
  for (const root of args.workspaceRoots) {
    leafNames.push(...(await readDirectoryNames(root)))
  }

  // Lowercased on both sides: the recorded cwd can differ in case from ours on case-insensitive
  // filesystems, and a missed bucket reissues a live path while a spurious one costs one name.
  const encodedParents = args.workspaceRoots
    .filter((root) => root.length > 0)
    .map((root) => encodeClaudeProjectPath(root).toLowerCase())
  if (encodedParents.length > 0) {
    const projectsDir = getClaudeProjectsDir(args.home ?? homedir(), args.env ?? process.env)
    for (const bucket of await readDirectoryNames(projectsDir)) {
      leafNames.push(...extractBucketLeafCandidates(bucket, encodedParents))
    }
  }

  return collectRetiredNamesFromLeafNames(leafNames)
}
