import { readdir } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { isAutoGeneratedCreatureBranchName } from '../shared/branch-name-from-work'
import { getRepoExecutionHostId } from '../shared/execution-host'
import { isFolderRepo } from '../shared/repo-kind'
import type { GlobalSettings, Repo } from '../shared/types'
import {
  encodeClaudeProjectPath,
  isClaudeProjectDirInScope
} from './ai-vault/claude-project-dir-encoding'
import {
  computeRemoteWorktreePath,
  computeWorktreePath,
  getWorktreePathSettings,
  hasRepoWorktreeBasePath
} from './ipc/worktree-logic'
import { worktreePathComparisonKey } from './ipc/worktree-path-comparison'

const RETIREMENT_PROBE_NAME = 'orca-retirement-probe'
const backfillsByStore = new WeakMap<object, Map<string, Promise<void>>>()

type RetirementReadStore = {
  getRetiredWorktreeNames(collisionKey: string): string[]
}
type RetirementWriteStore = {
  addRetiredWorktreeName(collisionKey: string, name: string): void
}
type RetirementBackfillStore = {
  mergeRetiredWorktreeNames(collisionKey: string, names: Iterable<string>): boolean
}
type RetirementPathSettings = Pick<GlobalSettings, 'nestWorkspaces' | 'workspaceDir'>

/** Why reuse the auto-rename predicate: it already defines "a name Orca picked, not the user", is
 *  already tested, and a second definition here drifted — its `-([2-9]\d*)` never matched `-10`. */
export function normalizeRetirableGeneratedName(name: string): string | null {
  const normalized = name.trim().toLowerCase()
  if (normalized.length > 256) {
    return null
  }
  return isAutoGeneratedCreatureBranchName(normalized) ? normalized : null
}

/** Why: over-retiring costs one name from a 552-entry pool; under-retiring reissues a path whose
 *  agent history is still on disk. So this matches generously and never tries to be exact. */
export function collectRetiredNamesFromLeafNames(leafNames: Iterable<string>): Set<string> {
  const retired = new Set<string>()
  for (const leafName of leafNames) {
    if (typeof leafName !== 'string' || leafName.length === 0) {
      continue
    }
    const normalized = normalizeRetirableGeneratedName(leafName)
    if (normalized) {
      retired.add(normalized)
    }
  }
  return retired
}

/** The workspace leaf is whatever the bucket has beyond its encoded parent. Deriving it from
 *  trailing dash segments instead makes a numerically named workspace retire its parent
 *  directory's name — and `orca` is in the pool. The first segment is also offered because an
 *  agent run from a subdirectory buckets the whole subpath. */
export function extractBucketLeafCandidates(
  bucketName: string,
  encodedParents: readonly string[]
): string[] {
  const bucket = bucketName.toLowerCase()
  for (const parent of encodedParents) {
    if (!parent || bucket === parent || !isClaudeProjectDirInScope(bucket, [parent])) {
      continue
    }
    const remainder = bucket.slice(parent.length + 1)
    if (!remainder) {
      continue
    }
    const firstSegment = remainder.split('-')[0]
    return remainder === firstSegment ? [remainder] : [remainder, firstSegment]
  }
  return []
}

function getRetirementProbePath(repo: Repo, settings: RetirementPathSettings): string {
  const pathSettings = getWorktreePathSettings(repo, settings)
  return repo.connectionId
    ? computeRemoteWorktreePath(RETIREMENT_PROBE_NAME, repo.path, pathSettings, {
        useConfiguredAbsolutePath: hasRepoWorktreeBasePath(repo)
      })
    : computeWorktreePath(RETIREMENT_PROBE_NAME, repo.path, pathSettings)
}

// Why: for a WSL repo the probe path costs a blocking `wsl.exe` call, and the create path plus
// every suggestion refresh asks for the same key. Inputs are all the key derives from.
const COLLISION_KEY_CACHE_MAX = 512
const collisionKeyCache = new Map<string, string>()

export function resetRetirementCollisionKeyCacheForTests(): void {
  collisionKeyCache.clear()
}

/** Identifies the cwd namespace a repo creates workspaces into. Two repos that would place a
 *  workspace of the same name at the same path share retirements; independent paths do not. */
export function getRetirementCollisionKey(repo: Repo, settings: RetirementPathSettings): string {
  const hostId = getRepoExecutionHostId(repo)
  const cacheKey = [
    hostId,
    repo.path,
    repo.worktreeBasePath ?? '',
    settings.workspaceDir,
    settings.nestWorkspaces ? 'nested' : 'flat'
  ].join('\u0000')
  const cached = collisionKeyCache.get(cacheKey)
  if (cached !== undefined) {
    return cached
  }
  const key = `${hostId}:${worktreePathComparisonKey(getRetirementProbePath(repo, settings))}`
  if (collisionKeyCache.size >= COLLISION_KEY_CACHE_MAX) {
    collisionKeyCache.clear()
  }
  collisionKeyCache.set(cacheKey, key)
  return key
}

export function getRetiredWorktreeNamesForRepo(
  store: RetirementReadStore,
  repo: Repo,
  settings: RetirementPathSettings
): string[] {
  if (isFolderRepo(repo)) {
    return []
  }
  return store.getRetiredWorktreeNames(getRetirementCollisionKey(repo, settings))
}

/** Records the name main actually used, not the one the client proposed — the create path can
 *  advance past a taken candidate. Call only for names Orca generated. */
export function retireGeneratedWorktreeName(
  store: RetirementWriteStore,
  repo: Repo,
  settings: RetirementPathSettings,
  name: string
): void {
  if (isFolderRepo(repo)) {
    return
  }
  store.addRetiredWorktreeName(getRetirementCollisionKey(repo, settings), name)
}

function parentPath(path: string): string {
  const trimmed = path.replace(/[/\\]+$/, '')
  const separatorIndex = Math.max(trimmed.lastIndexOf('/'), trimmed.lastIndexOf('\\'))
  return separatorIndex < 0 ? '' : trimmed.slice(0, separatorIndex)
}

export function ensureRetiredWorktreeNamesBackfilled(
  store: RetirementBackfillStore,
  repo: Repo,
  settings: RetirementPathSettings
): Promise<void> {
  // Remote workspaces keep their agent state on the execution host, which this scan cannot see.
  if (isFolderRepo(repo) || repo.connectionId) {
    return Promise.resolve()
  }
  let storeBackfills = backfillsByStore.get(store)
  if (!storeBackfills) {
    storeBackfills = new Map()
    backfillsByStore.set(store, storeBackfills)
  }
  const collisionKey = getRetirementCollisionKey(repo, settings)
  const existing = storeBackfills.get(collisionKey)
  if (existing) {
    return existing
  }
  const backfill = discoverRetiredWorktreeNames({
    workspaceRoots: [parentPath(getRetirementProbePath(repo, settings))]
  }).then((names) => {
    store.mergeRetiredWorktreeNames(collisionKey, names)
  })
  storeBackfills.set(collisionKey, backfill)
  return backfill
}

async function readDirectoryNames(path: string): Promise<string[]> {
  try {
    const entries = await readdir(path, { withFileTypes: true })
    return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name)
  } catch {
    // Missing or unreadable roots are normal: the agent may never have run on this machine.
    return []
  }
}

/** Claude buckets its per-conversation state under a directory derived from the workspace cwd. A
 *  bucket surviving its workspace is exactly the evidence we need: the name was used, the
 *  directory is gone, and reissuing the name would hand the next occupant that conversation.
 *  CLAUDE_CONFIG_DIR relocates the whole state root, buckets included.
 *
 *  Codex is deliberately not scanned: it records the cwd inside
 *  `sessions/YYYY/MM/DD/rollout-*.jsonl` rather than in a directory name, so seeding from it would
 *  mean parsing user conversation files. Names spent only under Codex before this feature shipped
 *  stay issuable; every name spent after it is recorded at create time regardless of agent. */
function getClaudeProjectsDir(home: string, env: NodeJS.ProcessEnv): string {
  const override = env.CLAUDE_CONFIG_DIR?.trim()
  return override ? join(override, 'projects') : join(home, '.claude', 'projects')
}

/** Discovers names already spent for a repo, for the one-time seed of the retirement registry.
 *  Local and best-effort by design — agent state for an SSH workspace lives on the execution host,
 *  so names used only there stay issuable until this host observes them. */
export async function discoverRetiredWorktreeNames(args: {
  workspaceRoots: readonly string[]
  home?: string
  env?: NodeJS.ProcessEnv
}): Promise<Set<string>> {
  const leafNames: string[] = []
  for (const root of args.workspaceRoots) {
    leafNames.push(...(await readDirectoryNames(root)))
  }

  // Lowercased on both sides: the recorded cwd can differ in case from ours on case-insensitive
  // filesystems, and a missed bucket reissues a live path while a spurious one costs one name.
  const encodedParents = args.workspaceRoots
    .filter((root) => root.length > 0)
    .map((root) => encodeClaudeProjectPath(root).toLowerCase())
  if (encodedParents.length > 0) {
    const projectsDir = getClaudeProjectsDir(args.home ?? homedir(), args.env ?? process.env)
    for (const bucket of await readDirectoryNames(projectsDir)) {
      leafNames.push(...extractBucketLeafCandidates(bucket, encodedParents))
    }
  }

  return collectRetiredNamesFromLeafNames(leafNames)
}
